# Generated by Django 4.2 on 2024-02-24 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_student_alter_post_options_alter_post_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('partner', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
