# Generated by Django 4.2 on 2024-02-24 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_userinfo_remove_adult_first_name_remove_adult_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='userinfo_ptr',
        ),
        migrations.DeleteModel(
            name='Adult',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
