# Generated by Django 4.2 on 2024-02-27 13:45

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_remove_student_userinfo_ptr_delete_adult_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField(default=18)),
            ],
        ),
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('new_posts', django.db.models.manager.Manager()),
            ],
        ),
    ]
